# Generated by Django 5.0 on 2023-12-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Course Categories'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='interested_category',
        ),
        migrations.AddField(
            model_name='student',
            name='interested_categories',
            field=models.ManyToManyField(blank=True, related_name='interested_students', to='main.coursecategory'),
        ),
    ]
