# Generated by Django 5.0 on 2023-12-10 04:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_address_teacher_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images'),
        ),
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
